name: Publish

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the two latest versions
        run: |
          BASE=${{ github.event.before }}
          echo "base=$(echo $BASE)" >> $GITHUB_ENV

      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install yarn
        run: npm install -g yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **\node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build libraries
        run: |
          yarn nx affected:build --prod --base=$base
      - name: Version
        run: |
          yarn nx affected:libs --base=$base --target=version &&
          git push --tags &&
          for LIBRARY in $(yarn nx affected:libs --base=$base --plain | awk 'NR > 2 && $1 != "Done" { print $1 }')
          do
            cd ./dist/packages/$LIBRARY
            npm publish --registry https://npm.pkg.github.com --no-git-tag-version --no-push --yes
            cd ..
            cd ..
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
